### ISSUE TITLE
i think is error

### ISSUE THREAD

**Issue by lo-th** [FedUni/caliko#14]
hello in FabrikChain3D.java
on solveIK  Backward pass

end GLOBAL_HINGE and LOCAL_HINGE have
Utils.approximatelyEquals(cwConstraintDegs , FabrikJoint3D.MAX_CONSTRAINT_ANGLE_DEGS, 0.01f)
but should be 
Utils.approximatelyEquals(cwConstraintDegs , -FabrikJoint3D.MAX_CONSTRAINT_ANGLE_DEGS, 0.01f)

**Comment by alansley** [comment]
Yup - you're absolutely correct, good eyes! =D

I've added those missing minus signs and pushed the changes.

Cheers!
