### ISSUE TITLE
Hello World guide

### ISSUE THREAD

**Issue by salamanders** [FedUni/caliko#20]
Request: a "Hello World" caliko guide, or maybe the right tests to copy code from.

I have what (I think) is a pretty straightforward 2d need, but I wasn't sure where to start.

* Two fixed points, side by side (let's say at -5,0 and 5,0)
* Each with an arm of length ... uh... 15.
* Each can travel from 15degrees (from X axis) to 165 degrees. (wave your hands in the air like you just don't... anyway.)
* Then those two arms have a second arm bone, let's say length 10.
* which can travel much more, a relative -170 to 170. (like those floppy used car balloons!)
* and they each come together at the same point, which joins together the two arms.

(Imagine clasping your hands together above your head: your neck is the origin, your shoulders are the -5,+5, your upper arms are the 15, your forearms are the 10s, you are holding a single spray paint can with both of your hands, and you are spray painting the wall using just your shoulder rotation muscles)

Do I start with the demos?  The tests?

**Comment by salamanders** [comment]
Ah, I found this: https://usermanual.wiki/Pdf/calikouserguide.1180712306/view Seems to be going in the right direction at page 10!

**Comment by alansley** [comment]
Haha, was going to say - you know there's a user guide, right? =D

**Comment by salamanders** [comment]
Actually, I didn't! It isn't linked to from the GitHub home page. I found it by googling and hoping.

**Comment by alansley** [comment]
Fair enough, although it does come packaged with each SoniFight release, as well as a jar of the JavaDoc API documentation.

Anyway, added a documentation section to the README.md with a link to the docs.

Cheers!

**Comment by salamanders** [comment]
Runs like a dream, thank you!  "Two arms each holding the same target"

```kotlin
val structure = FabrikStructure2D()

val armLeft = FabrikChain2D().apply {
    setFixedBaseMode(true)
    baseboneConstraintType = FabrikChain2D.BaseboneConstraintType2D.GLOBAL_ABSOLUTE
    baseboneConstraintUV = UP
    addBone(FabrikBone2D(Vec2f(-5f, 0f), Vec2f(-5f, 13f)).apply {
        clockwiseConstraintDegs = 80f
        anticlockwiseConstraintDegs = 160f
    })
    addConsecutiveConstrainedBone(UP, 24f, 160f, 10f)
}

val armRight = FabrikChain2D().apply {
    setFixedBaseMode(true)
    baseboneConstraintType = FabrikChain2D.BaseboneConstraintType2D.GLOBAL_ABSOLUTE
    baseboneConstraintUV = UP
    addBone(FabrikBone2D(Vec2f(5f, 0f), Vec2f(5f, 13f)).apply {
        clockwiseConstraintDegs = 160f
        anticlockwiseConstraintDegs = 80f
    })
    addConsecutiveConstrainedBone(UP, 24f, 10f, 160f)
}

structure.addChain(armLeft)
structure.addChain(armRight)

val target = Vec2f(-30f, 5f)
structure.solveForTarget(target)
structure.debug(target=target)


```

**Comment by alansley** [comment]
Nice one - I'm happy you're happy! =D
