### ISSUE TITLE
Make a Java 7 compilable version of the library

### ISSUE THREAD

**Issue by dai-ichi** [FedUni/caliko#8]
The library requires Java 1.8 in order to build.  However, most (all?) versions of Android are limited to Java 1.7 (with only very limited support of certain 1.8 features).   This makes the distribution .jar files useless for Android development.

The compilation problems are not very serious.  In au.edu.federation.utils.Util there is a reference to Float.BYTES that only exists in 1.8.  Hardcoding that value to "4" fixes the issue.  I've only done this in my local copy of the core, but it appears during the maven build that similar issues exist in demo and visualization as well.

**Comment by alansley** [comment]
While Float.BYTES might be the only core issue, Java 1.7 doesn't support lambda functions which are used elsewhere in the code. These could be worked around - will have a think / chat with people about the best way to do this and get back to you.

**Comment by dai-ichi** [comment]
Yep, you are right.   At the time I was only interested in the core (which after making the Float.BYTES -> 4 change builds correctly).   So I ignored the demo and visualization packages--the mvn build errors only showed the same "Float.BYTES" symbol missing error.   But that was because the compiler exited after that pass.   If I fix the symbols in demo and visualization the compiler then shows the construct errors.

Remember, though, that my issue is that the jar files were unusable for android development.   Demo and Visualization wouldn't be usable in android anyway because of the use of OpenGLWindow.  It would be nice if they built anyway so that desktop Java 1.7 environments could see that wonderfully constructed demo.

**Comment by alansley** [comment]
Working on it - expect updates =D

**Comment by alansley** [comment]
If I was to maintain Java 7 compatibility then the best way would likely be to rewrite the methods which use lambda functions to use standard callback methods and then perhaps do a maven replace of Float.BYTES with the value 4. However, why don't you just upgrade to Java 1.8 and gain the speed, flexibility and security of it?

Also, not sure how the demos would work on Android without modification away from glfw. Input especially would need a massive rewrite to use onTouchEvent shenanigans.

**Comment by dai-ichi** [comment]
The objective of the project was to interface the mechanics of the arm with an android phone.   Unfortunately, Android does not support Java 8.  Android will only compile and run using Java 7.   The important thing about the project was your Caliko core (which works nicely with Java 7 with changes)--the demo/virtualization is unimportant because all of it would have to be re-engineered for the mobile environment; and that level of effort is unnecessary for Android.  However, switching a developer environment in Windows from 1.7 to 1.8 (to run your demo) and back again (to run Android Studio and build projects) is burdensome, so it would be nice if the demo would run in 1.7 so Android Developers wouldn't have to keep switching.

On the other hand, I would just be happy with a "core only" branch that built/ran in 1.7 so I don't have to include the entire core source tree in my project just to change one line of code.

Oh by the way, I am making a video of the final result.  It is kind of cool being able to move the arm meaningfully using android gestures.  It'll take a while because I have to first clean up my office--or people would see what kind of pig I am.

**Comment by jmsjr** [comment]
So you only need a caliko core JAR built with 1.7 bytecode ?
I am not familiar with Android development, but:

1) I presume you can take a pre-built JAR from a non-Android environment, and use the JAR in your Andriod app. If that is the case, and since caliko core does not have any other Maven dependencies ( apart from junit and mockito for unit testing ), then you can try adding a source 1.8 and a target of 1.7 in the maven-source-plugin in caliko/pom.xml ( **not** the aggregate POM ), like so: 

>       <plugin>
>        <groupId>org.apache.maven.plugins</groupId>
>        <artifactId>maven-source-plugin</artifactId>
>        <configuration>
>          <source>1.8</source>
>          <target>1.7</target>
>        </configuration>        
>      </plugin>

... in order to override the 1.8 target from the aggregate POM. Then build it in Linux / Windows, take the generated JAR artifact to your Android development, etc.

2) If you want to build caliko itself in Android and you are limited to Java 1.7, then change the above so that *both* source and target are 1.7 ( Then of course you remove the dependency on / remove the modules visualisation and demo ).

Since the core library does not rely on 1.8 syntax, either way will work ( tried both locally in that the demo still works ).

**Comment by dai-ichi** [comment]
Yes that works, but it will only compile in a 1.8 environment (obviously).   For android development, I always use a 1.7 environment.   We also try not to include jar files in our git source; we'd rather pull dependencies from projects... but I suppose an exception could be made.  It would be nice if the distributed .jar files you have already had a 1.7 compatible core.

**Comment by jmsjr** [comment]
See pull request:
https://github.com/FedUni/caliko/pull/12

**Comment by joediscar** [comment]
So cool!   I'll check it out as soon as I can.

**Comment by jmsjr** [comment]
Note that to use the 1.7 artifact, you will hace to use a classifier of jdk7

**Comment by alansley** [comment]
dai-ichi, are you happy to close this issue - or does it require any further work?

**Comment by dai-ichi** [comment]
Perfect.  Have you considered publishing it in the Maven repository?
